# Generated by Django 4.1.2 on 2022-10-22 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=200)),
                ('hash', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_tags_json', models.CharField(max_length=500)),
                ('dependency_labels_json', models.CharField(max_length=500)),
                ('ancestor_positions_json', models.CharField(max_length=500)),
                ('hash', models.CharField(max_length=32)),
                ('num_words', models.PositiveIntegerField()),
                ('is_root_verb', models.BooleanField(default=True)),
                ('is_root_imperative', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=45)),
                ('pos_tag', models.CharField(max_length=13)),
                ('dependency_label', models.CharField(blank=True, max_length=13)),
                ('count', models.PositiveBigIntegerField(default=1)),
                ('ancestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='poem.word')),
            ],
        ),
    ]
